---
#

- name: Check state of SAProuter SAPROUTTAB
  ansible.builtin.stat:
    path: "{{ saprouter_deployment_global_profile_dir }}/SAPROUTTAB"
  register: __saprouter_saprouttab_file_registered
  changed_when: false
  check_mode: false

- name: Generate SAProuter SAPROUTTAB
  ansible.builtin.template:
    src: "{{ saprouter_saprouttab_template }}"
    dest: "{{ saprouter_deployment_global_profile_dir }}/SAPROUTTAB"
    owner: "{{ saprouter_deployment_user_name }}"
    group: sapsys
    mode: '0644'
  when: >
    not __saprouter_saprouttab_file_registered.stat.exists or
    saprouter_regenerate_saprouttab_enabled | bool
