---
## Prepare SAProuter software source

- name: Check state of host SAProuter source directory - {{ saprouter_deployment_src_dir }}
  ansible.builtin.stat:
    path: "{{ saprouter_deployment_src_dir }}"
  register: __saprouter_deployment_file_registered
  changed_when: false
  check_mode: false

- name: Ensure host SAProuter source directory exists - {{ saprouter_deployment_src_dir }}
  ansible.builtin.file:
    path: "{{ saprouter_deployment_src_dir }}"
    state: directory
    owner: root
    group: sapsys
    mode: '0775'
  when: not __saprouter_deployment_file_registered.stat.exists

- name: Evaluate archive filenames in host SAProuter source directory are determined
  ansible.builtin.set_fact:
    __saprouter_deployment_source_sapcar_filename: "{{ saprouter_deployment_src_dir }}/SAPCAR"
    __saprouter_deployment_source_saprouter_sar_filename:
      "{{ saprouter_deployment_src_dir }}/{{ saprouter_deployment_bundle_saprouter_sar_file }}"
    __saprouter_deployment_source_sapcryptolib_sar_filename:
      "{{ saprouter_deployment_src_dir }}/{{ saprouter_deployment_bundle_sapcryptolib_sar_file }}"

- name: Ensure location of original SAPCAR is determined (local)
  ansible.builtin.set_fact:
    __saprouter_deployment_bundle_sapcar_remote_src: false
    __saprouter_deployment_bundle_sapcar_dir:
      "{{ saprouter_deployment_bundle_sapcar_local_dir | default(saprouter_deployment_bundle_local_dir) }}"
  when:
    - saprouter_deployment_bundle_sapcar_remote_dir is not defined
    - saprouter_deployment_bundle_sapcar_local_dir is defined or saprouter_deployment_bundle_local_dir is defined

- name: Ensure location of original SAPCAR is determined (remote)
  ansible.builtin.set_fact:
    __saprouter_deployment_bundle_sapcar_remote_src: true
    __saprouter_deployment_bundle_sapcar_dir:
      "{{ saprouter_deployment_bundle_sapcar_remote_dir | default(saprouter_deployment_bundle_remote_dir) }}"
  when:
    - saprouter_deployment_bundle_sapcar_local_dir is not defined
    - saprouter_deployment_bundle_sapcar_remote_dir is defined or saprouter_deployment_bundle_remote_dir is defined

- name: Ensure SAPCAR utility is copied into SAProuter host source directory
  ansible.builtin.copy:
    dest: "{{ __saprouter_deployment_source_sapcar_filename }}"
    src: "{{ __saprouter_deployment_bundle_sapcar_dir }}/{{ saprouter_deployment_bundle_sapcar_file }}"
    owner: root
    group: sapsys
    mode: '0775'
    remote_src: "{{ __saprouter_deployment_bundle_sapcar_remote_src }}"

- name: Ensure location bundle archives is determined (local)
  ansible.builtin.set_fact:
    __saprouter_deployment_bundle_remote_src: false
    __saprouter_deployment_bundle_dir:
      "{{ saprouter_deployment_bundle_local_dir }}"
  when:
    - saprouter_deployment_bundle_local_dir | d('') | length > 0

- name: Ensure location bundle archives is determined (remote)
  ansible.builtin.set_fact:
    __saprouter_deployment_bundle_remote_src: true
    __saprouter_deployment_bundle_dir:
      "{{ saprouter_deployment_bundle_remote_dir }}"
  when:
    - saprouter_deployment_bundle_remote_dir| d('') | length > 0

- name: Ensure bundle archives are copied into host source directory
  ansible.builtin.copy:
    dest: "{{ item.dest_filename }}"
    src: "{{ __saprouter_deployment_bundle_dir }}/{{ item.src_file }}"
    owner: root
    group: sapsys
    mode: '0775'
    remote_src: "{{ __saprouter_deployment_bundle_remote_src }}"
  when:
    - __saprouter_deployment_bundle_dir | d('') | length > 0
  with_items:
    - src_file: "{{ saprouter_deployment_bundle_saprouter_sar_file }}"
      dest_filename: "{{ __saprouter_deployment_source_saprouter_sar_filename }}"
    - src_file: "{{ saprouter_deployment_bundle_sapcryptolib_sar_file }}"
      dest_filename: "{{ __saprouter_deployment_source_sapcryptolib_sar_filename }}"

- name: Ensure host source directory of SAProuter is prepared - {{ saprouter_deployment_sid }}
  ansible.builtin.stat:
    path: "{{ item }}"
  register: __saprouter_deployment_file_registered
  failed_when: not __saprouter_deployment_file_registered.stat.exists
  with_items:
    - "{{ __saprouter_deployment_source_sapcar_filename }}"
    - "{{ __saprouter_deployment_source_saprouter_sar_filename }}"
    - "{{ __saprouter_deployment_source_sapcryptolib_sar_filename }}"

- name: Ensure SAPCAR utility is functional
  ansible.builtin.command: "{{ __saprouter_deployment_source_sapcar_filename }} --version"
  changed_when: false
  check_mode: false
