---
- name: Converge
  hosts: all
  tasks:
    - name: Ensure SAProuter instance is deployed
      vars:
        saprouter_deployment_bundle_local_dir: files/saprouter_deployment_bundle
        saprouter_deployment_bundle_saprouter_sar_file: saprouter_1011-80003478.sar
        saprouter_deployment_bundle_sapcryptolib_sar_file: SAPCRYPTOLIBP_8544-20011697.SAR
        saprouter_deployment_bundle_sapcar_file: SAPCAR_1115-70006178.EXE
      ansible.builtin.include_role:
        name: "mprusov.saprouter_deployment"
